version: '3.8'

services:
  xkx100:
    image: ghcr.io/fluffos/fluffos:master
    container_name: xkx100
    working_dir: /mudlib
    restart: unless-stopped
    volumes:
      - ./:/mudlib
    command: ["config.ini"]
